server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,mailing,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true