database:
  url: http://localhost:8050

mailing:
  url: http://localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test3
    username: admin
    password: 11111111
    driver-class-name: org.postgresql.Driver
