server:
  port: 8050

spring:
  liquibase:
    change-log: src/main/resources/db/changelog/master.xml
    changeLogFile: src/main/resources/db/changelog/master.xml
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, database, prometheus
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
