FROM openjdk:21

ARG JAR_FILE=microservices/mailing/target/mailing-1.0-SNAPSHOT.jar
ARG APP_FILE=application-docker.yaml
COPY ${JAR_FILE} mailing.jar
COPY ${APP_FILE} application.yaml
EXPOSE 8080
ENTRYPOINT ["java","-jar","/mailing.jar"]